name: GNNS
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.6.0=h313beb8_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h254cc4a_0
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - blas=1.0=openblas
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotlicffi=1.0.9.2=py311h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h191e429_0
  - certifi=2025.10.5=py311hca03da5_0
  - cffi=2.0.0=py311h3a083c1_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py311h48ca7d4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py311h0962b89_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - filelock=3.17.0=py311hca03da5_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.60.1=pyh7db6752_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py311h5c1b81f_0
  - graphite2=1.3.14=hc377ac9_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=he637ebf_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py311hca03da5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.1=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311hca03da5_0
  - jpeg=9f=h2f69dba_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - kiwisolver=1.4.8=py311h313beb8_0
  - krb5=1.21.3=h237132a_0
  - lark=1.3.0=pyhd8ed1ab_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libavif=1.1.1=h80987f9_0
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.2=hdc2269c_0
  - libiconv=1.16=h80987f9_3
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libopenblas=0.3.30=hf2bb037_0
  - libpng=1.6.39=h80987f9_0
  - libsodium=1.0.20=h99b78c6_0
  - libtiff=4.7.0=h91aec0a_0
  - libwebp=1.3.2=hf40cdb4_1
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.8=h0b34f26_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py311h80987f9_0
  - matplotlib=3.10.6=py311ha1ab1f8_0
  - matplotlib-base=3.10.6=py311h066045a_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py311hca03da5_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=py311hca03da5_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.3.3=py311hc95ac1c_1
  - numpy-base=2.3.3=py311h8087a70_1
  - openjpeg=2.5.2=hba36e21_1
  - openssl=3.5.4=h5503f6c_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py311h6dd570d_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py311h254cc4a_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py311hca03da5_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=10.1=py311h80987f9_0
  - pyobjc-framework-cocoa=10.1=py311hb094c41_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.13=h19e8193_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytorch=2.5.1=py3.11_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h80987f9_0
  - pyzmq=27.1.0=py311h854a7ef_0
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=py311hca03da5_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.22.3=py311h2aea54e_0
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=py311hca03da5_0
  - terminado=0.18.1=pyh31c8845_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.3.0=pyhcf101f3_0
  - torchaudio=2.5.1=py311_cpu
  - torchvision=0.20.1=py311_cpu
  - tornado=6.5.1=py311h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py311hca03da5_0
  - typing_extensions=4.15.0=py311hca03da5_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py311h80987f9_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=py311hca03da5_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/GNNS
